version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  web:
    image: eu.gcr.io/eshop-trzos/eshop-core-{ENVIRONMENT}:{COMMIT_SHA}
    volumes:
      - .:/eshop-core
    entrypoint:
      - /bin/sh
      - ./kubernetes/test-script.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_HOST: db
    command: sleep infinity
