# NODE PORTS

# core - staging
---
apiVersion: v1
kind: Service
metadata:
  name: core-np
  labels:
    app: eshop-core
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: core-port
  selector:
    app: eshop-core
---

# email-sender - staging
---
apiVersion: v1
kind: Service
metadata:
  name: es-np
  labels:
    app: eshop-email-sender
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: es-port
  selector:
    app: eshop-email-sender
---

# INGRESS - core

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eshop-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: core-np
          servicePort: core-port
---

# INGRESS - email-sender
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eshop-es-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: es-np
          servicePort: es-port
---
